language: ruby
rvm:
- 2.2.4
before_install: gem update --remote bundler
install:
- bundle install --retry=3
script:
- bundle exec rspec
- bundle exec rubocop --config .rubocop.yml
services: "-postgresql"
env:
  global:
    - secure: "jZ2w89YyuVl61H0Kig5aVM4gHbh476H3uwMINo048MPDGLHYIB89K/yNUV8SHW/TReZ/obNOGGYU4TKfLltxddHc0bIo5zyuwe+c9TpuIjltoRzrrSYm/WzOk6Hd6od4l4hUBQLB91gAYK2GkvNV/99AOokGyw/7vbBsrcmul4fIB1jTfU7FEhftBjHe+2yCUwBVo54s1/kPvu0CdFYkGjV5a8hIbevL5shl5xPED3oanf3zzBFUcqWS6s3UUsBPjeQgtc8j6U6+lgpfpQ1tUDEChp+P7Q6byEUtvhifwVIiNmezmdyuM/cjxXAz/MVDlCB1jauKw+u4C6p2pHWgb5GqWiuje3/WKwh2mri84VbUzhpMHh62D3kr8z41//Q7Txi1e3d/IlR6OLUrLWgBhaxaDE0AItOzTGrce31GWohyCwRY789OvFOWOkT4FPjrDvV7oXTvFbaQhm870Z9k9GO2dOhoeO+R7KQxWM5Cgcd3g+YTxtkBa7Py1lopb4FLhxED+cHu2/Y1dEgOPDlst+P8smnHpFqW3uKVqUxiV/MFv/PFJaob+N964hqKWp0W4I2BeY2AAovCDw73xGgmoFDvBAfqdCnYFdoVO1gZh7tIZ5PQTHaUp6xN7xF91Z8dJV4t5jvwcgbZpjEDGLqgceXQ0Wzh9OGKuFhlUAeiKJo="
    - secure: "YrkIZx1Ul1zt3Dd7hB8S2qkzu47393y5A2fav4OoBEzpZ+OXGLux10tYBrhm2lSc88v8hmIHX42okIsxBUSDjvuqiBUW44b7QvaTzN0IL605o9/TRGpRKK6ZWrp2TmWlxZ4ffaCmzEg7W/EszPegpb63BXaDr4REKPSwUhyv79Z1xa7j/As2aQ0GwV8HLLttFoDEIUBtujjlvFh2OvOWnx7agAmsDwBiMbBXqOi4DRuZXZZpiB3t1rahSXKLdLx/b6LdMMPcbAyB2oBRFSMmzwlW76IgIdrhssIXnHbmUHZtHXcd9WlX/mKtjhSL3DCTQ3E5OqrZFUucnkdigrTGzWfipKIycVWWsVM/VikQYjCZfOoJILf+NP1KJjl6hBf+2D+rlPkhTw7pKvmmrQjYe/CLvDQ5wYUukZ6lyuF9kovd1CpSvv9bNVsoGgLDz08sqtx+2nhV6TowpEiFaPZNlY5yYOd3gfMfXL+aAumF1ECsZF4b3NqT0CcRR6zqzDMrV8y9gSdjg1INllAAhoQcnK6CbIzcPfP4DHBBc+faDPyWXxsx7WFtG9VYqSDxtSkdGN9CHgo8x5C0ADAAinw12XfpbY9ADch7vXjFGm0enGMxEdrGs30YV7JXysPL6qRx0F4qvtEwP0vmFc5aI8uRTKQh+koLuRvQPZvdM5VBKeo="
    - secure: "AKedrbFktwabNqgbBI77orrmmBysswMXmSZpRa9gOrwp9wSVfuH7urXuwEIZg727hKuyQSdLQkRanMJ8VbCevL9MT60ccCan3OAcTRpJIvguGcVQHmkoT4Vt9p0FysLuHfefmgRgnJGAUvmlF7cE0O2e+QlT1egsHBYhEx6CveJUc+pc+j1mLa+O8K7blJ7IMJ+8CONlyb/JqpnowTj/lcPpVgMwx6lD+Nln1n8XdszIIcQQjaa2im8/73gaLYNM/vqSmaYITknuKpqDe4BR5964gWB1mOGXLIFnzbh/X2crffzHqzWdeKjmEWLxolxpppLpDlAHHCvBnNWMqdc3z+QrfXA5EtcK2yqjcWjzaJCcihj8RyllBp4zQOgMurOe5dNALXs7CHn+Cjlpz6GZdq2BRkAphZLzmkuvKUhnaer/GGOJAOpNrX/intJrE87S/n+sQ7pjsCiXU18Msy3qjg4uXjXpauO4J3DJaZJ//abUpeFa/B2DthWICE9P/iqGaj323ZNfKnkV31rFD1ra7TMMKYX+enSZTl8OxW12Qm0yf8VyTtRzXFg0fdsPVwMoGmNS6XrqnmFsDCPBHxgJaRTs5Et8oznWmUuWVKFaD5KWMWgMAuBmVOmm4MOdh0uBN9uQZISoYC6OvX2Eip9AVYOO60ed0p7Cd3CZ8BSHgeI="
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  run: "rake db:migrate"
  api_key:
    secure: 459db56a-dcee-4b7f-b896-fbbb6b681bf6
  app: chess-fusion
  on:
    repo: Team-Chess-Fusion/chess-fusion